FROM kittymac/silkroad:latest

WORKDIR /root/SilkRoad

COPY ./Makefile ./Makefile
COPY ./Package.swift ./Package.swift
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN /usr/bin/swift-build-all

RUN /usr/bin/patch-dependency Hitch SilkRoadFramework
RUN /usr/bin/patch-dependency Spanker SilkRoadFramework

